# Generated by Django 3.0.3 on 2020-02-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0003_barbershop_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbershop',
            old_name='areaid',
            new_name='area',
        ),
    ]
