# Generated by Django 3.0.3 on 2020-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0006_auto_20200226_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
