# Generated by Django 3.0.3 on 2020-03-03 16:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0007_auto_20200227_1300'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='barbershop',
            managers=[
                ('um', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('um', django.db.models.manager.Manager()),
            ],
        ),
    ]
