# Generated by Django 3.0.3 on 2020-03-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0008_auto_20200303_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='image',
            field=models.ImageField(blank=True, upload_to='barber-image'),
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, upload_to='customer-image'),
        ),
    ]
