# Generated by Django 3.0.3 on 2020-03-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0009_auto_20200304_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
