# Generated by Django 3.0.8 on 2020-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0010_auto_20200304_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
