# Generated by Django 3.0.8 on 2020-08-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0011_area_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='barbershop',
            managers=[
            ],
        ),
    ]
