# Generated by Django 3.0.8 on 2020-08-02 12:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ebarber', '0012_auto_20200801_1544'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='barbershop',
            managers=[
                ('um', django.db.models.manager.Manager()),
            ],
        ),
    ]
